### ISSUE TITLE
Fail to build with EFL 25

### ISSUE THREAD

**Issue by qumaciel** [wfx/enter#1]
Hi, 

First of all, thank you for creating this greeter!
I am trying to tie up a Manjaro build with lightdm and your greeter would be a nice addition to it.
 
I am getting a issue while running `sudo python setup.py install`. I have
```
efl 1.25.1
python-efl 1.25
```
and a get the following error:

```
running install
running build
running build_edc
compiling theme "default" from edc file: "data/themes/default/main.edc"
edje_cc -v -id data/themes/default -id data/themes/default/images -fd data/themes/default -fd data/themes/default/fonts -sd data/themes/default -sd data/themes/default/sounds data/themes/default/main.edc build/themes/default.edj
Warning: Image 'sessions_icon.png' not used
edje_cc: Image 'sessions_icon.png' in resource 'edje/image/1' will not be included as it is unused.
edje_cc: header: 0.00000
edje_cc: groups: 0.00524
edje_cc: scripts: 0.00000
edje_cc: lua scripts: 0.00000
edje_cc: source: 0.00047
edje_cc: fontmap: 0.00004
edje_cc: vectors: 0.00008
edje_cc: fonts: 0.00000
edje_cc: sounds: 0.00000
edje_cc: mo: 0.00000
edje_cc: vibrations: 0.00000
edje_cc: license: 0.00000
edje_cc: Wrote    450758 bytes ( 440Kb) for "edje/images/0" image entry "bg_radgrad.png" compress: [raw: 83.1%] [real: 77.6%]
edje_cc: Wrote       599 bytes (   1Kb) for "edje/images/1" image entry "session_unknown.png" compress: [raw: 92.3%] [real: 92.4%]
edje_cc: Wrote      3312 bytes (   3Kb) for "edje/images/2" image entry "power_icon.png" compress: [raw: 64.1%] [real: 34.3%]
edje_cc: Wrote      3048 bytes (   3Kb) for "edje/images/3" image entry "lang_icon.png" compress: [raw: 66.9%] [real: 21.5%]
edje_cc: Wrote     19256 bytes (  19Kb) for "edje/images/4" image entry "default_face.png" compress: [raw: 97.8%] [real: -32.9%]
edje_cc: Wrote     12486 bytes (  12Kb) for "edje/images/5" image entry "session_enlightenment.png" compress: [raw: 84.1%] [real: 36.5%]
edje_cc: Wrote      7516 bytes (   7Kb) for "edje/images/6" image entry "session_gnome.png" compress: [raw: 93.2%] [real: 93.2%]
edje_cc: Wrote      9691 bytes (   9Kb) for "edje/images/7" image entry "session_kde.png" compress: [raw: 91.2%] [real: 91.2%]
edje_cc: Wrote      1111 bytes (   1Kb) for "edje/images/8" image entry "session_epymc.png" compress: [raw: 87.9%] [real: 31.6%]
edje_cc: images: 0.58946
edje_cc: THREADS: 0.00000
edje_cc: Wrote       448 bytes (   0Kb) for "edje_file" header
edje_cc: THREADS: 0.00036
Summary:
  Wrote 8 collections
  Wrote 9 images
  Wrote 0 sounds
  Wrote 0 fonts
changing mode of build/themes/default.edj to 644
compiling theme "enter" from edc file: "data/themes/enter/main.edc"
edje_cc -v -id data/themes/enter -id data/themes/enter/images -fd data/themes/enter -fd data/themes/enter/fonts -sd data/themes/enter -sd data/themes/enter/sounds data/themes/enter/main.edc build/themes/enter.edj
Warning: Image 'underline.png' not used
edje_cc: Image 'underline.png' in resource 'edje/image/6' will not be included as it is unused.
Warning: Image 'sessions_icon.png' not used
edje_cc: Image 'sessions_icon.png' in resource 'edje/image/7' will not be included as it is unused.
Warning: Image 'session_enlightenment_small.png' not used
edje_cc: Image 'session_enlightenment_small.png' in resource 'edje/image/12' will not be included as it is unused.
Warning: Image 'session_unknow_small.png' not used
edje_cc: Image 'session_unknow_small.png' in resource 'edje/image/12' will not be included as it is unused.
Warning: Image 'session_unknow.png' not used
edje_cc: Image 'session_unknow.png' in resource 'edje/image/12' will not be included as it is unused.
Warning: Image 'session_kde_small.png' not used
edje_cc: Image 'session_kde_small.png' in resource 'edje/image/12' will not be included as it is unused.
Warning: Image 'session_gnome_small.png' not used
edje_cc: Image 'session_gnome_small.png' in resource 'edje/image/14' will not be included as it is unused.
edje_cc: Critical. GROUP enter/main - state 'focused:0' does not exist for part 'username_focused'; set in program 'username_focused'
error: command 'edje_cc' failed with exit status 255
```

**Comment by wfx** [comment]
Hi,
huh 6 year old code.
It need some refactoring (python 3 and more).
..
data/themes/enter/main.edc
..
If you look inside main.edc you see the "username_focused" part ... 
this only exist in the unfinished and broken enter theme
Please try it with the default one.

Am Di, 8. Dez, 2020 um 4:54 VORMITTAGS schrieb qumaciel 
<notifications@github.com>:

**Comment by qumaciel** [comment]
I appreciate your quick response!

> Hi, huh 6 year old code. It need some refactoring (python 3 and more). 

Yeah, I've figured, but worth a shot though. :smile: 

> If you look inside main.edc you see the "username_focused" part ... this only exist in the unfinished and broken enter theme. Please try it with the default one. 

I managed to build with default and some minor changes regarding the deprecated lightdm calls, but lightdm failed to start.

**Comment by wfx** [comment]
I think it can't found the theme.
Have you any error message?

wfx

08.12.2020 19:05:25 qumaciel <notifications@github.com>:

**Comment by qumaciel** [comment]
I've got nothing enlightening:
```
[FAILED] Failed to start Light Display Manager
[FAILED] Failed to start Light Display Manager
.
.
.
```
while booting.

and, via `sudo dmesg | grep lightdm` , I've got
```
[    5.489995] audit: type=1130 audit(1607466113.315:31): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[    5.841710] audit: type=1130 audit(1607466113.668:32): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    5.841719] audit: type=1131 audit(1607466113.668:33): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    5.851609] audit: type=1130 audit(1607466113.678:34): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[    6.203283] audit: type=1130 audit(1607466114.032:35): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    6.203293] audit: type=1131 audit(1607466114.032:36): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    6.216990] audit: type=1130 audit(1607466114.042:37): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[    6.568717] audit: type=1130 audit(1607466114.395:38): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    6.568728] audit: type=1131 audit(1607466114.395:39): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lightdm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Comment by wfx** [comment]
Is something in /var/log/lightdm.log* ?

Am Di, 8. Dez, 2020 um 2:36 NACHMITTAGS schrieb qumaciel 
<notifications@github.com>:

**Comment by qumaciel** [comment]
with `xorg-server-xephyr` I ran `lightdm --test-mode --debug`,
```
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=1000 PID=13995
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf.d/20-optimus-manager.conf
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Running in user mode
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
[+0.00s] DEBUG: Monitoring logind for seats
[+0.00s] DEBUG: New seat added from logind: seat0
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.00s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.00s] DEBUG: Seat seat0: Starting
[+0.00s] DEBUG: Seat seat0: Creating greeter session
[+0.00s] DEBUG: Seat seat0: Failed to find session configuration lightdm-efl-greeter 
[+0.00s] DEBUG: Seat seat0: Failed to create greeter session
[+0.00s] DEBUG: Failed to start seat: seat0
```
running just `lightdm-efl-greeter`, I got
```
[INFO] lightdm-efl-greeter:27   efl logging initialized
/usr/bin/lightdm-efl-greeter:337: DeprecationWarning: LightDM.Greeter.connect_sync is deprecated
  self.greeter.connect_sync()
Traceback (most recent call last):
  File "/usr/bin/lightdm-efl-greeter", line 412, in <module>
    app = EnterApplication()
  File "/usr/bin/lightdm-efl-greeter", line 337, in __init__
    self.greeter.connect_sync()
gi.repository.GLib.Error: lightdm_greeter_error: Unable to determine socket to daemon (1)
```

I get the same result changing the deprecated `connect_sync()` to `connect_to_daemon_sync()`

**Comment by wfx** [comment]
Am Mi, 9. Dez, 2020 um 5:56 VORMITTAGS schrieb qumaciel 
<notifications@github.com>:
> Failed to find session configuration lightdm-efl-greeter

..
[+0.00s] DEBUG: Seat seat0: Failed to find session configuration 
lightdm-efl-greeter
..

Bingo, light cant find the greeter. Check the path. maybe you have it 
localy.

**Comment by qumaciel** [comment]
that is wierd.
 I have everything in place.
```
/usr/bin/lightdm-efl-greeter
/usr/share/xgreeters/lightdm-efl-greeter.desktop
/usr/share/lightdm-efl-greeter/themes/default.edj
/usr/share/lightdm-efl-greeter/themes/enter.edj
/usr/share/lightdm-efl-greeter/themes/kuuko.edj
/usr/lib/python3.8/site-packages/lightdm_efl_greeter-0.0.1-py3.8.egg-info
```
they are right beside my GTK greeter

**Comment by wfx** [comment]
Paths look good Check modes and python version ( <3.0 it was written 
with 2.7 i think)

Am Mi, 9. Dez, 2020 um 7:34 VORMITTAGS schrieb qumaciel 
<notifications@github.com>:

**Comment by wfx** [comment]
i update it ... but i cant test it ( no efl or ligthdm is installed :)

Am Mi, 9. Dez, 2020 um 4:50 NACHMITTAGS schrieb Wolfgang Morawetz 
<wolfgang.morawetz@gmail.com>:

**Comment by qumaciel** [comment]
> i update it ... but i cant test it ( no efl or ligthdm is installed :) 

I apologize for the inconvenience.

but I got new erros :smile: 
in `/var/log/lightdm/seat0....... .log`
```
[INFO] lightdm-efl-greeter:30   efl logging initialized

** (process:607): WARNING **: 14:50:42.515: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
/usr/bin/lightdm-efl-greeter:46: PyGIWarning: LightDM was imported without specifying a version first. Use gi.require_version('LightDM', '1') before import to ensure that the right version gets loaded.
  from gi.repository import LightDM
/usr/bin/lightdm-efl-greeter:339: DeprecationWarning: LightDM.Greeter.connect_sync is deprecated
  self.greeter.connect_sync()
Traceback (most recent call last):
  File "/usr/bin/lightdm-efl-greeter", line 414, in <module>
    app = EnterApplication()
  File "/usr/bin/lightdm-efl-greeter", line 355, in __init__
    self.main_win = MainWin(self, not self.greeter.get_hide_users_hint())
  File "/usr/bin/lightdm-efl-greeter", line 85, in __init__
    self.theme_setup()
  File "/usr/bin/lightdm-efl-greeter", line 146, in theme_setup
    if os.path.exists(u.props.image):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
and in `/var/log/lighdm/lightdm.log`
```
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=592
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.01s] DEBUG: Could not run plymouth --ping: Failed to execute child process “plymouth” (No such file or directory)
[+0.01s] DEBUG: Using VT 7
[+0.01s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.01s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.01s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0
[+0.01s] DEBUG: XServer 0: Launching X Server
[+0.01s] DEBUG: Launching process 598: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.01s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.01s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.02s] WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
[+0.02s] DEBUG: Loading user config from /etc/lightdm/users.conf
[+0.02s] DEBUG: User someone added
[+0.34s] DEBUG: Got signal 10 from process 598
[+0.34s] DEBUG: XServer 0: Got signal from X server :0
[+0.34s] DEBUG: XServer 0: Connecting to XServer :0
[+0.34s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+0.34s] DEBUG: Session pid=604: Started with service 'lightdm-greeter', username 'lightdm'
[+0.35s] DEBUG: Session pid=604: Authentication complete with return value 0: Success
[+0.35s] DEBUG: Seat seat0: Session authenticated, running command
[+0.35s] DEBUG: Session pid=604: Running command /usr/bin/lightdm-efl-greeter
[+0.35s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+0.35s] DEBUG: Session pid=604: Logging to /var/log/lightdm/seat0-greeter.log
[+0.36s] DEBUG: Activating VT 7
[+0.36s] DEBUG: Activating login1 session c5
[+0.36s] DEBUG: Seat seat0 changes active session to c5
[+0.36s] DEBUG: Session c5 is already active
[+0.44s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
[+0.50s] DEBUG: Greeter closed communication channel
[+0.50s] DEBUG: Session pid=604: Exited with return value 1
[+0.50s] DEBUG: Seat seat0: Session stopped
[+0.50s] DEBUG: Seat seat0: Stopping; failed to start a greeter
[+0.50s] DEBUG: Seat seat0: Stopping
[+0.50s] DEBUG: Seat seat0: Stopping display server
[+0.50s] DEBUG: Sending signal 15 to process 598
[+0.50s] DEBUG: Seat seat0 changes active session to 
[+0.60s] DEBUG: Process 598 exited with return value 0
[+0.60s] DEBUG: XServer 0: X server stopped
[+0.60s] DEBUG: Releasing VT 7
[+0.60s] DEBUG: XServer 0: Removing X server authority /run/lightdm/root/:0
[+0.60s] DEBUG: Seat seat0: Display server stopped
[+0.60s] DEBUG: Seat seat0: Stopped
[+0.60s] DEBUG: Required seat has stopped
[+0.60s] DEBUG: Stopping display manager
[+0.60s] DEBUG: Display manager stopped
[+0.60s] DEBUG: Stopping daemon
[+0.60s] DEBUG: Exiting with return value 1
```

**Comment by qumaciel** [comment]
Btw., I'm testing in a virtualbox with a minimal manjaro build. I can share in case you are interested.

**Comment by qumaciel** [comment]
I've got it! It is working now!
I was missing the accountsservice package
(from: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837979](url))

Thank you!

**Comment by wfx** [comment]
Great! :)

Am Mi, 9. Dez, 2020 um 11:05 VORMITTAGS schrieb qumaciel 
<notifications@github.com>:
